import Navbar from './navbar'
import Footer from './footer'
import Head from 'next/head'
import Script from 'next/script';

export default function Layout({ children }) {
    return (
        <>
            <Script strategy="lazyOnload" src={`https://www.googletagmanager.com/gtag/js?id=G-G6YFEEGX0S`} />

            <Script strategy="lazyOnload">
                {`
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());
                    gtag('config', 'G-G6YFEEGX0S', {
                    page_path: window.location.pathname,
                    });
                `}
            </Script>
            <Head>
                <title>Ing. Guillermo Cuamea</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main>{children}</main>
            <Footer />
        </>
    )
}